influxdata/influxdb-client-csharp

- CHANGELOG.md
- Client.Test/App.config
- Client.Test/InfluxDbClientFactoryTest.cs
- Client.Test/ItWriteQueryApiTest.cs
- Client.Test/PointSettingsTest.cs
- Client.Test/PointTest.cs
- Client/Configurations/Influx2.cs
- Client/InfluxDBClientOptions.cs
- Client/README.md
- Client/WriteApi.cs
- Client/Writes/Point.cs
- Client/Writes/PointSettings.cs
> Default tags

- CHANGELOG.md
- Client.Core/Client.Core.csproj
- Client.Core/Internal/GzipHandler.cs
- Client.Test/GzipHandlerTest.cs
- Client.Test/InfluxDbClientTest.cs
- Client.Test/ItUsersApiTest.cs
- Client.Test/ItWriteQueryApiTest.cs
- Client/InfluxDBClient.cs
- Client/Internal/ApiClient.cs
- Client/README.md
- Client/WriteApi.cs
> #29: Added support for gzip compression of query response and write body

- .circleci/config.yml
- .gitignore
- Client.Core.Test/AbstractTest.cs
- Client.Test/ItInfluxDBClientTest.cs
- Client.Test/ItWriteQueryApiTest.cs
- Scripts/ci-deploy-snapshot.sh
- Scripts/ci-test.sh
> Added CircleCI configuration

- CHANGELOG.md
- Client.Test/ItTasksApiTest.cs
- Client.Test/ItWriteQueryApiTest.cs
- Client.Test/PointDataTest.cs
- Client/InfluxDB.Client.Api/Domain/TaskType.cs
- Client/InfluxDB.Client.Api/Domain/Tasks.cs
- Client/InfluxDB.Client.Api/Service/TasksService.cs
- Client/Internal/MeasurementMapper.cs
- Client/README.md
- Client/TasksApi.cs
- Client/WriteApi.cs
- Client/Writes/PointData.cs
- Examples/PlatformExample.cs
- OpenAPIGenerator/src/main/java/org/influxdata/codegen/InfluxCSharpGenerator.java
Closes #34
Renamed Point class to PointData and Task class to TaskType (improving the usability of this library).
> Renamed Point class to PointData and Task class to TaskType

- CHANGELOG.md
- Client/WriteApi.cs
> optimized serialization into LineProtocol

- README.md
Very simple change to update the readme file to use `PointData` rather than `Point`. CLA signed.
> Update readme to use PointData class

- CHANGELOG.md
- Client.Core/Internal/LoggingHandler.cs
- Client.Test/InfluxDbClientTest.cs
- Client.Test/ItWriteQueryApiTest.cs
> feat(logging): LogLevel Header also contains query parameters

- .circleci/config.yml
- CHANGELOG.md
- Client.Core.Test/AbstractTest.cs
- Client.Test/ItInfluxDBClientTest.cs
- Client.Test/ItTelegrafsApiTest.cs
- Scripts/ci-test.sh
- Scripts/influxdb-onboarding.sh
- Scripts/influxdb-restart.sh
> chore(ci): build over dotnet 3.0, 3.1 and test on WindowsServer

- CHANGELOG.md
- Client.Core/Client.Core.csproj
- Client.Legacy/Client.Legacy.csproj
- Client/Client.csproj
- Examples/Examples.csproj
- Scripts/ci-deploy-snapshot.sh
> chore(ci): deploy dev version into Nuget repository

- CHANGELOG.md
- Client.Core/Internal/AssemblyHelper.cs
- Client.Legacy.Test/FluxClientQueryTest.cs
- Client.Legacy/FluxClient.cs
- Client.Test/AssemblyHelperTest.cs
- Client.Test/InfluxDbClientTest.cs
- Client.Test/ItChecksApiTest.cs
- Client.Test/ItTasksApiTest.cs
- Client.Test/WriteApiTest.cs
- Client/InfluxDBClient.cs
> feat: add User-Agent request header

- CHANGELOG.md
- Client.Core/Flux/Internal/FluxCsvParser.cs
- Client.Legacy.Test/FluxCsvParserTest.cs
- Client.Test/ItChecksApiTest.cs
- Client.Test/ItTasksApiTest.cs
> fix: Correctly parse CSV where multiple results include multiple tables

- CHANGELOG.md
- Client.Legacy.Test/FluxClientPingTest.cs
- Client.Legacy.Test/FluxClientQueryTest.cs
- Client.Legacy/FluxClient.cs
- Client.Legacy/FluxConnectionOptions.cs
- Client.Legacy/README.md
> feat: add possibility to authenticate requests

- Client.Test/ItAuthorizationsApiTest.cs
- Client.Test/ItBucketsApiTest.cs
- Client.Test/ItSourcesApiTest.cs
> fix: cannot find buckets after delete an organization

- CHANGELOG.md
- Client.Test/ItWriteManyMeasurements.cs
- Client.Test/MeasurementMapperTest.cs
- Client/Internal/MeasurementMapper.cs
> feat: Optimized mapping of measurements into PointData

- CHANGELOG.md
- Client.Core/Client.Core.csproj
- Client.Core/Flux/Internal/FluxCsvParser.cs
> feat: update CsvHelper to [15.0.4,16.0)

- CHANGELOG.md
- Client.Test/InfluxDbClientFactoryTest.cs
- Client/InfluxDBClientFactory.cs
- Examples/InfluxDB18Example.cs
- README.md
> docs: Clarify how to use a client with InfluxDB 1.8

- CHANGELOG.md
- Client.Legacy/FluxClient.cs
- Client/InfluxDB.Client.Api/Service/AuthorizationsService.cs
- Client/InfluxDB.Client.Api/Service/BucketsService.cs
- Client/InfluxDB.Client.Api/Service/CellsService.cs
- Client/InfluxDB.Client.Api/Service/ChecksService.cs
- Client/InfluxDB.Client.Api/Service/DashboardsService.cs
- Client/InfluxDB.Client.Api/Service/DefaultService.cs
- Client/InfluxDB.Client.Api/Service/HealthService.cs
- Client/InfluxDB.Client.Api/Service/InfluxPackagesService.cs
- Client/InfluxDB.Client.Api/Service/LabelsService.cs
- Client/InfluxDB.Client.Api/Service/NotificationEndpointsService.cs
- Client/InfluxDB.Client.Api/Service/NotificationRulesService.cs
- Client/InfluxDB.Client.Api/Service/OperationLogsService.cs
- Client/InfluxDB.Client.Api/Service/OrganizationsService.cs
- Client/InfluxDB.Client.Api/Service/QueryService.cs
- Client/InfluxDB.Client.Api/Service/ReadyService.cs
- Client/InfluxDB.Client.Api/Service/RulesService.cs
- Client/InfluxDB.Client.Api/Service/ScraperTargetsService.cs
- Client/InfluxDB.Client.Api/Service/SecretsService.cs
- Client/InfluxDB.Client.Api/Service/SetupService.cs
- Client/InfluxDB.Client.Api/Service/SourcesService.cs
- Client/InfluxDB.Client.Api/Service/TasksService.cs
- Client/InfluxDB.Client.Api/Service/TelegrafsService.cs
- Client/InfluxDB.Client.Api/Service/TemplatesService.cs
- Client/InfluxDB.Client.Api/Service/UsersService.cs
- Client/InfluxDB.Client.Api/Service/VariablesService.cs
- Client/InfluxDB.Client.Api/Service/ViewsService.cs
- Client/InfluxDB.Client.Api/Service/WriteService.cs
- OpenAPIGenerator/src/main/resources/csharp/api.mustache
> fix: Avoid a deadlock caused by SynchronizationContext

- CHANGELOG.md
- Client.Test/AbstractItClientTest.cs
- Client.Test/InfluxDbClientFactoryTest.cs
- Client.Test/InfluxDbClientTest.cs
- Client.Test/ItDeleteApiTest.cs
- Client.Test/ItInfluxDBClientTest.cs
- Client.Test/ItMonitoringAlertingTest.cs
- Client.Test/ItTasksApiTest.cs
- Client.Test/ItWriteApiAsyncTest.cs
- Client.Test/ItWriteApiRaceTest.cs
- Client.Test/ItWriteManyMeasurements.cs
- Client.Test/ItWriteQueryApiTest.cs
- Client.Test/WriteApiAsyncTest.cs
- Client.Test/WriteApiTest.cs
- Client/InfluxDBClientFactory.cs
- Client/InfluxDBClientOptions.cs
- Client/README.md
- Examples/PlatformExample.cs
Closes #117 
There is a new method AuthenticateToken which accept token as a string
> feat: added support for string token

- .circleci/config.yml
- CHANGELOG.md
- Client.Test/AbstractItClientTest.cs
- Client.Test/ItBucketsApiTest.cs
- Client.Test/ItDeleteApiTest.cs
- Client.Test/ItScraperTargetsApiTest.cs
- Client.Test/ItWriteApiAsyncTest.cs
- Client.Test/ItWriteQueryApiTest.cs
- Client/README.md
- Examples/PlatformExample.cs
- README.md
- Scripts/influxdb-restart.sh
> chore: changed default port to 8086

- CHANGELOG.md
- Client.Core/Flux/Internal/FluxCsvParser.cs
- Client.Legacy.Test/FluxCsvParserTest.cs
- Client.Test/ItTelegrafsApiTest.cs
- Client/Writes/PointData.cs
- Scripts/ci-test.sh
Closes #134
CSV parser is able to parse export from UI
> feat: CSV parser is able to parse export from UI

- Client/README.md
- Examples/Examples.csproj
- Examples/FluxClientFactoryExample.cs
- Examples/FluxClientPocoExample.cs
- Examples/FluxClientSimpleExample.cs
- Examples/FluxExample.cs
- Examples/FluxRawExample.cs
- Examples/PlatformExample.cs
- Examples/PocoQueryWriteExample.cs
- Examples/RunExamples.cs
- Examples/WriteApiAsyncExample.cs
- prepared en example with mapping query to POCO with multiple tags and fields
> docs: added example how to query POCO with multiple tags and fields

- CHANGELOG.md
- Client/Client.csproj
Updates dependencies of Client.csproj
Should none of them have big changes, just performace improvements
> feat: updated Dependencies of Client

- .circleci/config.yml
- CHANGELOG.md
- Client.Core.Test/Client.Core.Test.csproj
- Client.Legacy.Test/Client.Legacy.Test.csproj
- Client.Linq.Test/Client.Linq.Test.csproj
- Client.Test/Client.Test.csproj
- Client/InfluxDB.Client.Api/Domain/PermissionResource.cs
- Examples/Examples.csproj
- Scripts/ci-test.sh
Added `dotnet6` to CI.
https://devblogs.microsoft.com/dotnet/announcing-net-6/
> chore: add dotnet6 to CI

- Scripts/ci-test.sh
> chore(ci): update trx2junit to 1.6.0 - .NET 6.0 supported

- CHANGELOG.md
Updated `CHANGELOG.md` for v4.
> docs: prepare changelog for v4.0

- CHANGELOG.md
- Client/README.md
- Examples/README.md
- Examples/RunExamples.cs
- Examples/WriteApiExample.cs
- Examples/WriteEventHandlerExample.cs
Closes https://github.com/influxdata/influxdb-client-csharp/issues/212
Added example how to use WriteAPI with `EventHandler`
> docs: WriteAPI EventHandler

- .circleci/config.yml
- Client.Legacy/Client.Legacy.csproj
- Client.Linq/Client.Linq.csproj
- Client/Client.csproj
Closes #394
Added README.md as package description:
https://www.nuget.org/packages/InfluxDB.Client.Linq/4.7.0-dev.8360
> docs: add README.md as package description

- .circleci/config.yml
- CHANGELOG.md
- Scripts/ci-test.sh
> chore(ci): add `.NET 7.0` to CI
