influxdata/influxdb-client-csharp

CHANGELOG.md, Client.Test/ItTasksApiTest.cs, Client.Test/ItWriteQueryApiTest.cs, Client/InfluxDB.Client.Api/Domain/CheckViewProperties.cs, Client/InfluxDB.Client.Api/Domain/Task.cs, Client/InfluxDB.Client.Api/Domain/TaskCreateRequest.cs, Client/InfluxDB.Client.Api/Service/QueryService.cs, Client/InfluxDB.Client.Api/Service/WriteService.cs, Client/QueryApi.cs, Client/README.md, Client/TasksApi.cs, Client/WriteApi.cs, Scripts/swagger.yml
=> QueryApi: Organization name and id are interchangeably

CHANGELOG.md, Client.Test/ItWriteQueryApiTest.cs, Client.Test/PointTest.cs, Client/Writes/Point.cs
Closes #31 
Drop NaN and infinity values from fields when writing to InfluxDB
=> #31: Skip NaN and infinity values

CHANGELOG.md, Client.Core/Flux/Internal/FluxCsvParser.cs, Client.Legacy.Test/FluxCsvParserTest.cs
=> FluxCSVParser uses a CultureInfo for parsing string to double

CHANGELOG.md, Client.Core/Client.Core.csproj, Client.Legacy/Client.Legacy.csproj, Client/Client.csproj
PackageIconUrl is deprecated => we have to use PackageIcon
=> fix: PackageIconUrl is deprecated => we have to use PackageIcon

CHANGELOG.md, Client.Test/ItWriteQueryApiTest.cs, Client.Test/WriteApiTest.cs, Client/WriteApi.cs
cc #53
`WriteApi` could be disposed after whole buffer is processed.
=> fix: WriteApi is disposed after a buffer is fully processed

CHANGELOG.md, Client.Test/ItWriteQueryApiTest.cs, Client/WriteApi.cs
=> fix: write buffer uses correct flush interval and batch size under heavy load

CHANGELOG.md, Client.Test/WriteApiTest.cs, Client/WriteApi.cs
=> fix: potentially hangs on of WriteApi.Dispose()

CHANGELOG.md, Client.Core/Exceptions/InfluxException.cs, Client.Core/Internal/AbstractQueryClient.cs, Client.Legacy.Test/FluxClientQueryTest.cs, Client.Legacy/FluxClient.cs, Client/InfluxDBClient.cs, Client/WriteApi.cs
Closes #80
The error response for queries is encoded as a `stream` not as a "simple" `string`.
=> fix: parsing error response for queries

CHANGELOG.md, Client.Test/InfluxDbClientTest.cs, Client.Test/ItBucketsApiTest.cs, Client.Test/ItOrganizationsApiTest.cs, Client.Test/ItUsersApiTest.cs, Client/Internal/ApiClient.cs
Releated-to https://github.com/influxdata/influxdb-client-python/issues/87
=> feat: remove trailing slash from connection URL

Client.Test/ItWriteApiRaceTest.cs, Client.Test/WriteApiTest.cs, Client/InfluxDBClient.cs, Client/WriteApi.cs
Alternative to https://github.com/influxdata/influxdb-client-csharp/pull/99
I believe this is better approach (less coupling)
The subject notification is synchronously therefore safe for use in this scenario.
=> fix: thread-safety disposing of clients

CHANGELOG.md, Client/WriteApi.cs
Changed from `Console.WriteLine` to `Trace.WriteLine` to avoid console output when disposing `WriteApi`.
=> fix: Remove console output when disposing WriteApi

CHANGELOG.md, Client.Test/ItWriteApiAsyncTest.cs, Client/InfluxDBClient.cs, Client/README.md, Client/WriteApiAsync.cs, Examples/RunExamples.cs, Examples/WriteApiAsyncExample.cs
Closes #23
Added WriteApiAsync for asynchronous write without batching.
=> feat: Add async/await Write API without batching

CHANGELOG.md, Client.Test/PointDataTest.cs, Client/Writes/PointData.cs
Related to https://github.com/influxdata/influxdb-client-java/issues/127
* serialization of `\n`, `\r` and `\t` to Line Protocol
* `=` is valid sign for measurement name
=> fix: serialization of `\n`, `\r` and `\t` to Line Protocol,  `=` is valid sign for measurement name 

CHANGELOG.md, Client.Legacy/FluxClient.cs, Client.Test/ItBucketsApiTest.cs, Client.Test/ItLabelsApiTest.cs, Client.Test/ItNotificationEndpointsApiTest.cs, Client.Test/ItSourcesApiTest.cs, Client.Test/ItTasksApiTest.cs, Client.Test/ItUsersApiTest.cs, Client/AuthorizationsApi.cs, Client/BucketsApi.cs, Client/ChecksApi.cs, Client/InfluxDBClient.cs, Client/LabelsApi.cs, Client/NotificationEndpointsApi.cs, Client/NotificationRulesApi.cs, Client/OrganizationsApi.cs, Client/ScraperTargetsApi.cs, Client/SourcesApi.cs, Client/TasksApi.cs, Client/TelegrafsApi.cs, Client/UsersApi.cs
Closes #108
Replaced useless .ContinueWith in Api by direct call
=> fix: Replaced useless .ContinueWith in Api by direct call (#108)

CHANGELOG.md, Client.Test/WriteApiAsyncTest.cs, Client.Test/WriteApiTest.cs, Client/WriteApiAsync.cs
Closes #112
Fixed unnecessary API call when writing collection of DataPoints.
=> fix: unnecessary API call when writing collection of DataPoints

.circleci/config.yml, CHANGELOG.md, Client.Core.Test/Client.Core.Test.csproj, Client.Core/Client.Core.csproj, Client.Core/Exceptions/InfluxException.cs, Client.Core/Flux/Domain/FluxRecord.cs, Client.Core/Flux/Internal/FluxCsvParser.cs, Client.Core/Flux/Internal/FluxResultMapper.cs, Client.Core/Internal/AbstractQueryClient.cs, Client.Legacy.Test/Client.Legacy.Test.csproj, Client.Legacy.Test/FluxCsvParserTest.cs, Client.Legacy.Test/FluxResultMapperTest.cs, Client.Legacy/Client.Legacy.csproj, Client.Test/AbstractItClientTest.cs, Client.Test/Client.Test.csproj, Client.Test/WriteApiTest.cs, Client/Client.csproj, Client/QueryApi.cs, Examples/Examples.csproj, Scripts/ci-test.sh
This adds [`IAsyncEnumerable<T>`](https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8) support to the QueryAPI for .NET Standard 2.1 deployments. To support .NET Standard 2.1, client and client projects were modified to dual target .NET standard 2.1 and 2.0.
Closes #119 - both timestamp issue and suggested `IAsyncEnumerable` feature
=> feat: added IAsyncEnumerable<T> query overloads to QueryAPI

CHANGELOG.md, Client.Core/Exceptions/InfluxException.cs, Client.Test/RetryAttemptTest.cs, Client.Test/WriteApiTest.cs, Client/Internal/RetryAttempt.cs, Client/README.md, Client/WriteApi.cs, Client/WriteOptions.cs
1. default value for `RetryInterval` is 5_000
1. added exponential backoff strategy for batch writes
1. added `MaxRetries` - the number of max retries when write fails - `3`
1. added `MaxRetryDelay` -  the maximum delay between each retry attempt in milliseconds - `180_000`
1. added `ExponentialBase` -  the base for the exponential retry delay, the next delay is computed as `RetryInterval * ExponentialBase^(attempts-1) + random(JitterInterval)` 
1. retry also network strategy
1. other http request doesn't have retry strategy
=> feat: add exponential backoff strategy for retry

CHANGELOG.md, Client.Test/AbstractItClientTest.cs, Client.Test/WriteApiTest.cs, Client/OrganizationsApi.cs, Client/Writes/Events.cs
The message looks like:
_The retriable error occurred during writing of data. Reason: 'org 04014de4ed590000 has exceeded limited_write plan limit'. Retry in 5000ms._
=> feat: improved logging message for retries

CHANGELOG.md, Client.Test/App.config, Client.Test/InfluxDbClientFactoryTest.cs, Client.Test/ItWriteApiRaceTest.cs, Client.Test/ItWriteQueryApiTest.cs, Client/InfluxDBClientOptions.cs
Closes #142 
Added validation that a configuration is present when is client configured via file.
=> fix: validate configuration when is client configured via file

CHANGELOG.md, Client.Core/Client.Core.csproj, Scripts/ci-test.sh
Probably closes #141
- Update RestSharp to 106.11.7 to avoid https://github.com/restsharp/RestSharp/issues/1321
=> chore: update RestSharp to 106.11.7

CHANGELOG.md, Client.Core/Client.Core.csproj
In order to avoid warnings with our code base we would like to update the csvhelper library to a more recent version which nonetheless doesn't introduce breaking changes
I would have liked but it is not quite clear how to set up the dependencies for a successful test run. A windows download for influx db v2 doesn't seem to be available?
=> chore: update of csvhelper to v18

CHANGELOG.md, Client.Test/ItWriteApiAsyncTest.cs, Client.Test/PointDataTest.cs, Client/Writes/PointData.cs
Closes #149
The unsigned numbers are serialized with `u` postfix.
=> fix: added supports for unsigned numbers

CHANGELOG.md, Client.Core/Client.Core.csproj
=> fix: Remove Unnecesary dependencies

CHANGELOG.md, Client.Test/ApiClientTest.cs, Client.Test/ItDeleteApiTest.cs, Client/InfluxDB.Client.Api/Client/ApiClient.cs
Closes #167 
The `DateTime` is serialized into UTC to satisfy `RFC3339Nano` format.
=> fix: DateTime is always serialized into UTC

CHANGELOG.md, Client/InfluxDB.Client.Api/Domain/BadStatement.cs, Client/InfluxDB.Client.Api/Domain/BooleanLiteral.cs, Client/InfluxDB.Client.Api/Domain/BuiltinStatement.cs, Client/InfluxDB.Client.Api/Domain/DateTimeLiteral.cs, Client/InfluxDB.Client.Api/Domain/DurationLiteral.cs, Client/InfluxDB.Client.Api/Domain/ExpressionStatement.cs, Client/InfluxDB.Client.Api/Domain/FloatLiteral.cs, Client/InfluxDB.Client.Api/Domain/IntegerLiteral.cs, Client/InfluxDB.Client.Api/Domain/OptionStatement.cs, Client/InfluxDB.Client.Api/Domain/PipeLiteral.cs, Client/InfluxDB.Client.Api/Domain/RegexpLiteral.cs, Client/InfluxDB.Client.Api/Domain/ReturnStatement.cs, Client/InfluxDB.Client.Api/Domain/StringLiteral.cs, Client/InfluxDB.Client.Api/Domain/TestStatement.cs, Client/InfluxDB.Client.Api/Domain/UnsignedIntegerLiteral.cs
Related to #146
Fixed domain structure for Flux AST.
=> fix: correct structure for Flux AST

CHANGELOG.md, Client.Core.Test/AbstractMockServerTest.cs, Client.Core.Test/Client.Core.Test.csproj, Client.Core/Flux/Internal/AttributesCache.cs, Client.Core/Flux/Internal/FluxResultMapper.cs, Client.Core/Flux/Internal/IFluxResultMapper.cs, Client.Core/Internal/AbstractQueryClient.cs, Client.Core/Internal/LoggingHandler.cs, Client.Legacy/FluxClient.cs, Client.Test/Client.Test.csproj, Client.Test/GzipHandlerTest.cs, Client.Test/InfluxDbClientTest.cs, Client.Test/ItBucketsApiTest.cs, Client.Test/QueryApiSyncTest.cs, Client.Test/RetryAttemptTest.cs, Client/IDomainObjectMapper.cs, Client/InfluxDBClient.cs, Client/Internal/DefaultDomainObjectMapper.cs, Client/QueryApi.cs, Client/QueryApiSync.cs, Client/README.md, Client/WriteApi.cs, Client/WriteApiAsync.cs, Examples/CustomDomainMapping.cs, Examples/InfluxDB18Example.cs, Examples/RunExamples.cs, Examples/SynchronousQuery.cs, README.md
Related to #146 
- Added `QueryApiSync` for synchronous querying
- Added `IDomainObjectMapper` for custom mapping DomainObject from/to InfluxDB
=> feat: add QuerySyncApi, add possibility to use custom mapper from/to DomainObject

CHANGELOG.md, Client/InfluxDB.Client.Api/Client/ApiClient.cs, Client/InfluxDB.Client.Api/Service/AuthorizationsService.cs, Client/InfluxDB.Client.Api/Service/BucketsService.cs, Client/InfluxDB.Client.Api/Service/CellsService.cs, Client/InfluxDB.Client.Api/Service/ChecksService.cs, Client/InfluxDB.Client.Api/Service/DBRPsService.cs, Client/InfluxDB.Client.Api/Service/DashboardsService.cs, Client/InfluxDB.Client.Api/Service/DefaultService.cs, Client/InfluxDB.Client.Api/Service/HealthService.cs, Client/InfluxDB.Client.Api/Service/LabelsService.cs, Client/InfluxDB.Client.Api/Service/NotificationEndpointsService.cs, Client/InfluxDB.Client.Api/Service/NotificationRulesService.cs, Client/InfluxDB.Client.Api/Service/OrganizationsService.cs, Client/InfluxDB.Client.Api/Service/QueryService.cs, Client/InfluxDB.Client.Api/Service/ReadyService.cs, Client/InfluxDB.Client.Api/Service/RulesService.cs, Client/InfluxDB.Client.Api/Service/ScraperTargetsService.cs, Client/InfluxDB.Client.Api/Service/SecretsService.cs, Client/InfluxDB.Client.Api/Service/SetupService.cs, Client/InfluxDB.Client.Api/Service/SourcesService.cs, Client/InfluxDB.Client.Api/Service/TasksService.cs, Client/InfluxDB.Client.Api/Service/TelegrafsService.cs, Client/InfluxDB.Client.Api/Service/TemplatesService.cs, Client/InfluxDB.Client.Api/Service/UsersService.cs, Client/InfluxDB.Client.Api/Service/VariablesService.cs, Client/InfluxDB.Client.Api/Service/ViewsService.cs, Client/InfluxDB.Client.Api/Service/WriteService.cs
Related to #173 
Added possibility to use `CancellationToken` in our REST API
=> feat: allow to use `CancellationToken` in our REST API

CHANGELOG.md, Client/WriteApiAsync.cs
Closes #173 
WriteApiAsync method invocations can now be cancelled by providing a CancellationToken.
The CancellationToken is forwarded to the (new) underlying REST Api.
=> feat: add CancellationToken support in WriteApiAsync (#173)

CHANGELOG.md, Client.Test/PointDataBuilderTest.cs, Client/Writes/PointData.Builder.cs, Client/Writes/PointData.cs
Closes #178 
A Builder for PointData, loosely modeled after Collection.Immutable Builders.
=> feat: add mutable Builder for PointData (#178)

CHANGELOG.md, Client.Core/Internal/AbstractQueryClient.cs, Client.Legacy/FluxClient.cs, Client.Test/QueryApiTest.cs
Closes #177
Uses optimised request type for streaming query response.
=> fix: remove download overhead for Queries

.circleci/config.yml, .codecov.yml, CHANGELOG.md, Client.Core.Test/Client.Core.Test.csproj, Client.Legacy.Test/Client.Legacy.Test.csproj, Client.Linq.Test/Client.Linq.Test.csproj, Client.Test/Client.Test.csproj, Examples/Examples.csproj, Scripts/ci-test.sh
- added build for `dotnet5`
- fixed code coverage report: https://codecov.io/gh/influxdata/influxdb-client-csharp/branch/fix%2Fci-coverage
=> chore(ci): add build for dotnet5, fix code coverage report

CHANGELOG.md, Client.Test/WriteApiTest.cs, Client/README.md, Client/WriteApi.cs, Client/Writes/Events.cs
Closes #176 
Propagate runtime exception to `EventHandler`.
=> fix: propagate runtime exception to EventHandler

CHANGELOG.md, Client.Linq.Test/InfluxDBQueryVisitorTest.cs, Client.Linq.Test/ItInfluxDBQueryableTest.cs, Client.Linq.Test/QueryAggregatorTest.cs, Client.Linq/Internal/QueryAggregator.cs, Client.Linq/README.md
The LINQ driver always use `group()` function to achieve of producing only one output table.
=> feat(linq): use `group()` function in output Flux query

CHANGELOG.md, Client.Core.Test/AbstractMockServerTest.cs, Client.Core.Test/HttpExceptionTest.cs, Client.Core/Exceptions/InfluxException.cs, Client.Test/InfluxDbClientTest.cs, Client.Test/ItAuthorizationsApiTest.cs, Client.Test/ItBucketsApiTest.cs, Client.Test/ItChecksApiTest.cs, Client.Test/ItInfluxDBClientTest.cs, Client.Test/ItLabelsApiTest.cs, Client.Test/ItNotificationEndpointsApiTest.cs, Client.Test/ItNotificationRulesApiTest.cs, Client.Test/ItOrganizationsApiTest.cs, Client.Test/ItScraperTargetsApiTest.cs, Client.Test/ItSourcesApiTest.cs, Client.Test/ItTasksApiTest.cs, Client.Test/ItTelegrafsApiTest.cs, Client.Test/ItUsersApiTest.cs, Client.Test/WriteApiTest.cs
Closes #114
The client produce concrete exception e.g. `UnauthorizedException` instead of generic `HttpException`.
=> feat: produce a typed HTTP exception

.circleci/config.yml, CHANGELOG.md, Client.Linq.Test/InfluxDBQueryVisitorTest.cs, Client.Linq.Test/QueryAggregatorTest.cs, Client.Linq/Internal/QueryAggregator.cs, Client.Linq/README.md
The `pivot()` and `drop()` function was switch to achieve better performance - https://github.com/influxdata/EAR/issues/2182
=> feat(linq): switch pivot() and drop() function to achieve better perf

CHANGELOG.md, Client.Test/InfluxDbClientTest.cs, Client/InfluxDBClient.cs, Client/README.md
Closes #191
Added possibility to create services without API implementation.
=> fix: create services without API implementation

CHANGELOG.md, Client.Test/WriteApiAsyncTest.cs, Client/WriteApiAsync.cs
Closes #107
Closes #109
Added possibility to handle HTTP response from InfluxDB server when user uses `WriteApiAsync`.
=> feat(write): add possibility to handle HTTP response from InfluxDB server

CHANGELOG.md, Client.Linq.Test/InfluxDBQueryVisitorTest.cs, Client.Linq.Test/ItInfluxDBQueryableTest.cs, Client.Linq.Test/QueryAggregatorTest.cs, Client.Linq/InfluxDBQueryable.cs, Client.Linq/Internal/QueryAggregator.cs, Client.Linq/Internal/QueryExecutor.cs, Client.Linq/Internal/QueryGenerationContext.cs, Client.Linq/Internal/QueryVisitor.cs, Client.Linq/README.md
Closes #196 
The LINQ driver produces Flux Query optimized for querying one time series.
=> feat(linq): optimize Flux Query for querying one time-series

CHANGELOG.md, Client.Linq.Test/DomainObjects.cs, Client.Linq.Test/InfluxDBQueryVisitorTest.cs, Client.Linq/Internal/Expressions/AssignmentValue.cs, Client.Linq/Internal/QueryExpressionTreeVisitor.cs, Client.Linq/Internal/QueryVisitor.cs, Client.Linq/Internal/VariableAggregator.cs, Client.Linq/README.md, Client/InfluxDB.Client.Api/Domain/PermissionResource.cs
Closes #201 
Create correct Flux AST if property type of Entity is `tag` and isn't `string`.
=> fix(linq): Flux AST for Tag parameters which are not `String`

CHANGELOG.md, Client.Test/RetryAttemptTest.cs, Client.Test/WriteApiTest.cs, Client/Internal/RetryAttempt.cs, Client/README.md, Client/WriteOptions.cs
Improves exponential random retry strategy in write api like in python client https://github.com/influxdata/influxdb-client-python/pull/225
Delay is computed using random exponential backoff as a random value within the interval  ``retryInterval * exponentialBase^(attempts-1)`` and ``retryInterval * exponentialBase^(attempts)``. 
Example for ``retryInterval=5_000, exponentialBase=2, maxRetryDelay=125_000, total=5``
Retry delays are random distributed values within the ranges of ``[5_000-10_000, 10_000-20_000, 20_000-40_000, 40_000-80_000, 80_000-125_000]``
=> feat: exponential random retry

CHANGELOG.md, Client.Core/Client.Core.csproj, Client.Core/Flux/Internal/FluxCsvParser.cs, Client/Client.csproj
Closes #208
Update dependencies:
- CsvHelper to 27.1.0
- Newtonsoft.Json 13.0.1
- NodaTime to 3.0.5
- NodaTime.Serialization.JsonNet to 3.0.0
- Microsoft.Extensions.ObjectPool to 5.0.7
=> chore: update dependencies

Client.Legacy/README.md, Client.Linq/README.md, Client/README.md, README.md
Added unified documentation section.
=> docs: add client docs links

CHANGELOG.md, Client.Core/Flux/Exceptions/FluxCsvParserException.cs, Client.Core/Flux/Internal/FluxCsvParser.cs, Client.Legacy.Test/FluxCsvParserTest.cs
Related to https://github.com/influxdata/influxdb-client-java/issues/239
Fixed parsing `Inf+` for [histogram() function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/histogram/).
```csv
#group,false,false,true,true,true,true,true,true,true,true,false,false
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,string,string,string,string,double,double
#default,_result,,,,,,,,,,,
,result,table,_start,_stop,_field,_measurement,language,license,name,owner,le,_value
,,0,2021-06-23T06:50:11.897825012Z,2021-06-25T06:50:11.897825012Z,stars,github_repository,C#,MIT License,influxdb-client-csharp,influxdata,0,0
,,0,2021-06-23T06:50:11.897825012Z,2021-06-25T06:50:11.897825012Z,stars,github_repository,C#,MIT …
```
=> fix: parsing infinite numbers

CHANGELOG.md, Client.Test/ItTasksApiTest.cs, Client/Internal/ApiClient.cs
Closes #
I changed the way the session cookie is set in the request because the way it was done before didn't work (the "Cookie" header is overwritten somewhere).
I also added the session cookie to the signout-Request as it was missing there.
[x] Rebased/mergeable
[x] dotnet test completes successfully
[x] Commit messages are in semantic format
[x] Sign CLA (if not already signed)
=> fix: cookie handling in normal requests and signout

CHANGELOG.md, Client.Core/Client.Core.csproj, Client.Core/Flux/Internal/FluxResultMapper.cs, Client.Core/Flux/Internal/IFluxResultMapper.cs, Client.Core/Internal/AbstractQueryClient.cs, Client.Legacy.Test/FluxClientQueryTest.cs, Client.Legacy/Client.Legacy.csproj, Client.Linq/Client.Linq.csproj, Client.Test/AssemblyHelperTest.cs, Client.Test/InfluxDbClientTest.cs, Client.Test/QueryApiTest.cs, Client.Test/WriteApiTest.cs, Client/Client.csproj, Client/Internal/DefaultDomainObjectMapper.cs, Client/QueryApi.cs, Examples/CustomDomainMapping.cs, Examples/CustomDomainMappingAndLinq.cs, Examples/Examples.csproj, Examples/PocoQueryWriteExample.cs, Examples/QueryLinqCloud.cs
Closes #230 
This commit will add an overload to `QueryAsync` to allow a `Type` as parameter for the POCO object.
=> feat: add QueryAsync overload with Type parameter (#230)

CHANGELOG.md, Client.Core.Test/AbstractMockServerTest.cs, Client.Test/InfluxDbClientFactoryTest.cs, Client.Test/InfluxDbClientTest.cs, Client/Configurations/Influx2.cs, Client/InfluxDBClientOptions.cs, Client/Internal/ApiClient.cs, Client/README.md
1. Add possibility to follow HTTP redirects
2. Documentation for HTTP Proxies and redirects
=> feat: add possibility to follow HTTP redirects

CHANGELOG.md, Client.Linq.Test/DomainObjects.cs, Client.Linq.Test/InfluxDBQueryVisitorTest.cs, Client.Linq/Internal/VariableAggregator.cs
Closes #235
Fixed mapping `long` type in LINQ expressions.
=> fix: mapping long type into AST

CHANGELOG.md, Client.Linq.Test/Client.Linq.Test.csproj, Client.Linq.Test/ItInfluxDBQueryableTest.cs, Client.Linq/Client.Linq.csproj, Client.Linq/InfluxDBQueryable.cs, Client.Linq/Internal/QueryExecutor.cs, Client.Linq/README.md, Client.Test/QueryApiTest.cs, Client/QueryApi.cs
Closes #238 
Added support for asynchronous queries for LINQ driver.
=> feat(linq): add support for Async queries

CHANGELOG.md, Client/InfluxDB.Client.Api/Domain/PermissionResource.cs, Client/Internal/ApiClient.cs
Closes #262 
Use the returned session cookie name instead of assuming "session". InfluxDB 2.1 has changed the name of the cookie; for OSS in particular, it returns _influxdb-oss-session_ instead.
Please discard the PR if it's not satisfactory, but this fix did work for me.
=> Using the cookie name that InfluxDB 2.1 returns instead of assuming "session"

CHANGELOG.md, Client.Test/InfluxDbClientFactoryTest.cs, Client/Configurations/Influx2.cs, Client/InfluxDBClientOptions.cs, Client/Internal/ApiClient.cs
Add option to accept self-signed certificates like in influx client libraries for other languages e.g. https://github.com/influxdata/influxdb-client-python
=> feat:  add option to accept self-signed certificates

CHANGELOG.md, Client/InfluxDB.Client.Api/Domain/PermissionResource.cs
Added missing `PermissionResource` types.
=> fix: add missing PermissionResources from Cloud API definition

CHANGELOG.md, Client.Core/Flux/Internal/FluxResultMapper.cs, Client.Legacy.Test/FluxResultMapperTest.cs
Closes #280
Fixed serialisation of InfluxDB's response to POCO with optional DateTime type.
=> fix: serialize to nullable DateTime

CHANGELOG.md, Client.Linq.Test/DomainObjects.cs, Client.Linq.Test/InfluxDBQueryVisitorTest.cs, Client.Linq.Test/ItInfluxDBQueryableTest.cs, Client.Linq.Test/VariableAggregatorTest.cs, Client.Linq/InfluxDBQueryable.cs, Client.Linq/Internal/QueryAggregator.cs, Client.Linq/Internal/QueryExpressionTreeVisitor.cs, Client.Linq/Internal/VariableAggregator.cs, Client.Linq/README.md, Client/InfluxDB.Client.Api/Domain/Duration.cs
Closes #278 
Add support to use `aggregateWindow` in LINQ expression:
```c#
var query = from s in InfluxDBQueryable<Sensor>.Queryable("my-bucket", "my-org", _queryApi)
where s.Timestamp.AggregateWindow(TimeSpan.FromSeconds(20), TimeSpan.FromSeconds(40), "mean")
where s.Value == 5
select s;
```
=> feat: supports aggregateWindow in LINQ expressions

CHANGELOG.md, Client.Core/Client.Core.csproj
1. Updated RestSharp to `107.3.0`.
2. Set upcoming client version to `4.0.0-rc1`.
=> chore: update RestSharp to 107.3.0

CHANGELOG.md, Client.Linq.Test/InfluxDBQueryVisitorTest.cs, Client.Linq/InfluxDBQueryable.cs, Client.Linq/Internal/QueryAggregator.cs, Client.Linq/README.md
Closes #279
Add possibility to generate Flux query without `pivot()` function (`LINQ`).
=> feat(linq): add possibility to generate Flux query without `pivot()` function

CHANGELOG.md, Client.Legacy/FluxClient.cs, Client.Test/InfluxDbClientTest.cs, Client.Test/ItTasksApiTest.cs, Client/AuthorizationsApi.cs, Client/BucketsApi.cs, Client/ChecksApi.cs, Client/DeleteApi.cs, Client/LabelsApi.cs, Client/NotificationEndpointsApi.cs, Client/NotificationRulesApi.cs, Client/OrganizationsApi.cs, Client/ScraperTargetsApi.cs, Client/SourcesApi.cs, Client/TasksApi.cs, Client/TelegrafsApi.cs, Client/UsersApi.cs
Related to https://github.com/influxdata/influxdb-client-csharp/issues/228#issuecomment-1043157838
1. Removed useless `orgId` argument from `GetRunsAsync`
2. Async APIs uses `CancellationToken` in all `async` methods
3. Added Migration Notice in `CHANGELOG.md`
=> feat: uses `CancellationToken` in all async methods

CHANGELOG.md, Client.Test/ItAuthorizationsApiTest.cs, Client.Test/ItDeleteApiTest.cs, Client.Test/ItTasksApiTest.cs, Client.Test/ItWriteApiAsyncTest.cs, Client.Test/ItWriteApiRaceTest.cs, Client.Test/ItWriteQueryApiTest.cs, Client/InfluxDB.Client.Api/Domain/PermissionResource.cs, Client/README.md, Examples/ManagementExample.cs, Examples/PlatformExample.cs
The `PermissionResource.Type` is not constant value and can evolve as the API of InfluxDB changing. 
=>
Change type of `PermissionResource.Type` to `string`.
=> fix: change type of `PermissionResource.type` to `string` to avoid exception for non-existing item

CHANGELOG.md, Client/InfluxDB.Client.Api/Domain/CheckBase.cs
Related to https://github.com/influxdata/openapi/pull/268
Changed type of `CheckBase.LatestCompleted` to `DateTime`.
=> fix: type of `CheckBase.LatestCompleted` is `DateTime`

CHANGELOG.md, Client.Test/PointDataTest.cs, Client/Writes/PointData.cs, Client/Writes/PointSettings.cs
Optimized serialization `PointData` into LineProtocol.
```c#
[Test]
public void ToLineProtocolPerformance()
{
var points = new List<PointData>();
for (var i = 0; i < 1000000; i++)
{
points.Add(PointData.Measurement("h2o")
.Tag("location", "europe")
.Field("level", 2));
}
var pointSettings = new PointSettings();
var stopwatch = new Stopwatch();
stopwatch.Start();
foreach (var point in points)
{
point.ToLineProtocol(pointSettings);
}
stopwatch.Stop();
Console.WriteLine($"Elapsed milliseconds: {stopwatch.Elapsed.TotalMilliseconds}");
}
```
vs
=> feat: optimize serialization `PointData` into LineProtocol

CHANGELOG.md, Client.Test/PointDataBuilderTest.cs, Client.Test/PointDataTest.cs, Client/Writes/PointData.Builder.cs, Client/Writes/PointData.cs
Closes #276
Added possibility to put generic type object as a field in `PointData` and `PointData.Builder`.
=> feat: add possibility to put generic type object as a value for `PointData` and `PointData.Builder`

CHANGELOG.md, Client.Core/Internal/AbstractRestClient.cs, Client.Test/InfluxDbClientTest.cs, Client/InfluxDBClient.cs
Closes #296
Fixed getting version from `X-Influxdb-Version` header.
=> fix: get version from `X-Influxdb-Version` header

CHANGELOG.md, Client.Test/InfluxDbClientTest.cs, Client/Internal/ApiClient.cs
Closes #302
The `CookieContainer` doesn't set Cookies if there is a redirect to other domain, we have to use custom Authenticator.
=> fix: Authentication Cookies follow redirects

CHANGELOG.md, Client.Linq.Test/InfluxDBQueryVisitorTest.cs, Client.Linq/Internal/QueryExpressionTreeVisitor.cs
Closes #306
Fixed generated Flux Query for inline joins of binary operator:
```c#
var query = from s in InfluxDBQueryable<SensorDateTimeOffset>.Queryable("my-bucket", "my-org", _queryApi)
where s.Timestamp >= start && s.Timestamp < stop && s.SensorId == "id-1"
select s;
```
=> fix(linq): query expression for inline joins of binary operators

CHANGELOG.md, Client.Linq.Test/InfluxDBQueryVisitorTest.cs, Client.Linq/InfluxDBQueryable.cs, Client.Linq/Internal/NodeTypes/InfluxDBNodeTypeProvider.cs, Client.Linq/Internal/NodeTypes/TakeLastNodeType.cs, Client.Linq/Internal/QueryAggregator.cs, Client.Linq/Internal/QueryVisitor.cs, Client.Linq/README.md
Closes #307
Added support for `TakeLast` LINQ expression:
```c#
var query = (from s in InfluxDBQueryable<Sensor>.Queryable("my-bucket", "my-org", queryApi)
select s)
.TakeLast(10);
```
=> feat(linq): add support for TakeLast expression

CHANGELOG.md, Client.Test/WriteApiAsyncTest.cs, Client/WriteApiAsync.cs
Related to https://github.com/influxdata/influxdb-client-csharp/issues/311
Fixed using default `org` and `bucket` in `WriteApiAsync`.
=> fix: use default org and bucket

CHANGELOG.md, Client/Configurations/Influx2.cs, Client/InfluxDB.Client.Api/Client/Configuration.cs, Client/InfluxDBClientFactory.cs, Client/InfluxDBClientOptions.cs, Client/README.md
Related to https://github.com/influxdata/influxdb-client-csharp/issues/88#issuecomment-1109685642
Clarified the meaning of `timeout`.
=> docs: clarify `timeout` option

CHANGELOG.md, Client/QueryApi.cs, Client/QueryApiSync.cs, Examples/ParametrizedQuery.cs, Examples/README.md, Examples/RunExamples.cs
Added an example how to use parametrised query.
=> feat: add parametrized query example

.circleci/config.yml, CHANGELOG.md, Client.Core/Internal/AbstractQueryClient.cs, Client.Core/Internal/RestSharpExtensions.cs, Client.Test/ItWriteQueryApiTest.cs, Client.Test/QueryApiTest.cs, Scripts/reformat-code.sh
Closes #310
1. Fixed decompressing Gzipped data
2. Updated JetBrains.ReSharper.GlobalTools (code formatter) to 2022.1.0 3. 
3. Fixed logging HTTP headers from streaming request
=> fix: decompress Gzipped data

CHANGELOG.md, Client.Linq.Test/InfluxDBQueryVisitorTest.cs, Client.Linq/InfluxDBQueryable.cs, Client.Linq/Internal/QueryAggregator.cs, Client.Linq/README.md, Client.Test/AbstractItClientTest.cs
Closes #318
Add possibility to align `limit` and `tail` before `pivot`:
Limit():
Before:
After:
Tail():
Before:
After:
=> feat: Optionally align limit() and tail() before pivot() function

CHANGELOG.md, Client.Linq.Test/InfluxDBQueryVisitorTest.cs, Client.Linq.Test/ItInfluxDBQueryableTest.cs, Client.Linq/InfluxDBQueryable.cs, Client.Linq/Internal/QueryVisitor.cs, Client.Linq/README.md
Closes #320 
Possibility to specify default value for `start` and `stop` parameter of range function:
```c#
var settings = new QueryableOptimizerSettings
{
RangeStartValue = DateTime.UtcNow.AddHours(-24),
RangeStopValue = DateTime.UtcNow.AddHours(1)
};
var query = from s in InfluxDBQueryable<Sensor>.Queryable("my-bucket", "my-org", queryApi, settings)
select s;
```
=> feat(linq) add possibility to specify default value for `start` and `stop` parameter of range function

CHANGELOG.md, Client.Test/InfluxDbClientTest.cs, Client/InfluxDBClientOptions.cs, Client/Internal/ApiClient.cs, Scripts/ci-test.sh
Closes #321
Add possibility to custom validation of SSL certificates:
```c#
var cert = new X509Certificate2("path_to_file");
var options = new InfluxDBClientOptions.Builder()
.Url("http://localhost:8086")
.AuthenticateToken("my-token")
.RemoteCertificateValidationCallback((sender, certificate, chain, errors) => 
errors == SslPolicyErrors.None || string.Equals(cert.Thumbprint, certificate?.GetCertHashString(), StringComparison.InvariantCultureIgnoreCase))
.Build();
using var client = InfluxDBClientFactory.Create(options);
```
=> feat: Add callback function for handling the SSL Certificate Validation

CHANGELOG.md, Client.Legacy/FluxClient.cs, Client.Test/InfluxDbClientTest.cs, Client/AuthorizationsApi.cs, Client/BucketsApi.cs, Client/ChecksApi.cs, Client/DeleteApi.cs, Client/InfluxDBClient.cs, Client/InvokableScriptsApi.cs, Client/LabelsApi.cs, Client/NotificationEndpointsApi.cs, Client/NotificationRulesApi.cs, Client/OrganizationsApi.cs, Client/QueryApi.cs, Client/QueryApiSync.cs, Client/ScraperTargetsApi.cs, Client/SourcesApi.cs, Client/TasksApi.cs, Client/TelegrafsApi.cs, Client/UsersApi.cs, Client/WriteApi.cs, Client/WriteApiAsync.cs
Closes #325 
Added interfaces to APIs to be able to use `moq` library:
```c#
var mockClient = new Mock<IInfluxDBClient>();
var mockQueryApi = new Mock<IQueryApiSync>();
mockClient
.Setup(library => library.GetQueryApiSync(null))
.Returns(mockQueryApi.Object);
var mockTables = new List<FluxTable> { new FluxTable() };
mockQueryApi
.Setup(api => api.QuerySync("from(...", "my-org", CancellationToken.None))
.Returns(mockTables);
var tables = mockClient.Object.GetQueryApiSync().QuerySync("from(...", "my-org");
Assert.AreEqual(mockTables, tables);
```
=> feat: add interfaces to client's APIs

CHANGELOG.md, Client.Core.Test/Client.Core.Test.csproj, Client.Core/Client.Core.csproj, Client.Core/Internal/AbstractQueryClient.cs, Client.Core/Internal/RestSharpExtensions.cs, Client.Legacy.Test/Client.Legacy.Test.csproj, Client.Legacy.Test/FluxClientTest.cs, Client.Legacy/FluxClient.cs, Client.Linq.Test/Client.Linq.Test.csproj, Client.Test/Client.Test.csproj, Client/Client.csproj, Client/InfluxDB.Client.Api/Client/ApiClient.cs, Client/Internal/ApiClient.cs
Updated `RestSharp` to `108.0.1` and
- NodaTime to 3.1.0
- JsonSubTypes to 1.9.0
- Microsoft.Extensions.ObjectPool to 6.0.5
- Microsoft.NET.Test.Sdk to 17.2.0
- NUnit to 3.13.3
- WireMock.Net to 1.4.43
- Moq to 4.18.1
- Tomlyn.Signed to 0.14.3
=> chore: update RestSharp to `108.0.1` and other dependencies

CHANGELOG.md, Client.Core/Internal/LoggingHandler.cs, Client.Test/InfluxDbClientTest.cs
Redacted `Authorization` HTTP header from log.
=> fix: redact the Authorization HTTP header from log

CHANGELOG.md, Client.Test/ItTasksApiTest.cs, Client/TasksApi.cs
Related to https://github.com/influxdata/influxdb-client-python/issues/490
Append `task option` at the end of script. It allows create task with following Flux:
```
procTotal = from(bucket: "example-bucket")
|> range(start: -5m)
|> filter(fn: (r) => r._measurement == "processes" and r._field == "total")
procTotal
```
=> fix: append task option at the end of script

CHANGELOG.md, Client.Core.Test/AbstractTest.cs, Client.Linq.Test/DomainObjects.cs, Client.Linq.Test/InfluxDBQueryVariableTest.cs, Client.Linq/Internal/VariableAggregator.cs, Client.Test/AbstractItClientTest.cs, Client.Test/ItMonitoringAlertingTest.cs
Added support for `double` types in LINQ expression.
=> fix: support for `double` types in LINQ expression

CHANGELOG.md, Client/InfluxDBClient.cs
Closes #359
Designates HealthAsync() as obsolete in interface as well
=> fix: designe `HealthAsync()` as obsolete in interface

CHANGELOG.md, Client.Core/Client.Core.csproj, Client.Core/Internal/RestSharpExtensions.cs
1. Updated `RestSharp` to `108.0.2`
2. Use builtin support for synchronous HTTP requests from `RestSharp`
=> chore(deps): upgrade RestSharp, use builtin support for `synchronous` requests

CHANGELOG.md, Client.Core/Flux/Serialization/AnnotatedCsvParser.cs, Client.Legacy.Test/FluxCsvParserTest.cs
Closes #389
Expose `FluxCsvParser` as `AnnotatedCsvParser` for uses in third party integration.
=> feat: expose `FluxCsvParser` as `AnnotatedCsvParser`

CHANGELOG.md, Client.Test/PointDataTest.cs, Client.Test/WriteApiTest.cs, Client/Writes/PointData.cs
Closes #441
This PR allows to use `new DateTime(2015, 10, 15, 8, 20, 15, DateTimeKind.Local);` or `new DateTime(2015, 10, 15, 8, 20, 15, DateTimeKind.Unspecified)` as a timestamp for `PointData`:
```c#
var dateTime = new DateTime(2015, 10, 15, 8, 20, 15, DateTimeKind.Unspecified);
var point = PointData.Measurement("h2o")
.Tag("location", "europe")
.Field("level", 2)
.Timestamp(new DateTime(2015, 10, 15, 8, 20, 15, DateTimeKind.Unspecified), WritePrecision.Ms);
```
=> feat: allow to use `DateTimeKind.Local` and `DateTimeKind.Local` as a timestamp for data point

CHANGELOG.md, Client.Test/MeasurementMapperTest.cs, Client.Test/PointDataTest.cs, Client/Writes/PointData.cs
This reverts commit c4b64ae35966c688042f80eb1992ff63f63168c6.
=> Revert "fix: use g17 format for doubles (#434)"

.circleci/config.yml, CHANGELOG.md, Client.Linq.Test/InfluxDBQueryVisitorTest.cs, Client.Linq/Internal/QueryExpressionTreeVisitor.cs
Closes #461
Fixed passing aggregation function to `AggregateWindow`.
=> fix: Aggregation function in LINQ expressions

.circleci/config.yml, CHANGELOG.md, Client.Core/Client.Core.csproj, Client.Core/Internal/AbstractQueryClient.cs, Client.Core/Internal/RestSharpExtensions.cs, Client.Legacy/FluxClient.cs, Client.Test/WriteApiAsyncTest.cs, Client/Internal/ApiClient.cs, Client/InvokableScriptsApi.cs, Client/QueryApi.cs, Client/QueryApiSync.cs
Closes #494
Closes #501
Closes #504
Updated RestSharp to `110.1.0`.
We cannot use  110.2.0 due the https://github.com/restsharp/RestSharp/issues/2072.
=> chore: update RestSharp to `110.1.0`

CHANGELOG.md, Client.Test/ApiClientTest.cs, Client.Test/InfluxDbClientFactoryTest.cs, Client/InfluxDBClientOptions.cs, Client/Internal/ApiClient.cs
Add httpclient as  a part of InfluxbOption to allow injection of custom HttpMessageHandler(https://github.com/influxdata/influxdb-client-csharp/issues/516).
_Briefly describe your proposed changes: 
The caller can create a RestClient themselves through this constructor 'public RestClient(HttpClient httpClient, RestClientOptions options, bool disposeHttpClient = false)'. And this HttpClientMessageHandler instances will be managed by the dependency injection container.
It is also recommended in Microsoft documentation to send HTTP requests by injecting an HTTP client instead of creating an HTTP client instance every time(https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-7.0).
=> feat: add HttpClient as a part of InfluxDBClientOptions

CHANGELOG.md, Client.Linq.Test/ItInfluxDBQueryableTest.cs, Client.Linq/Internal/QueryAggregator.cs, Client.Linq/Internal/QueryExpressionTreeVisitor.cs
=> fix: chaining multiple condition in LINQ query

CHANGELOG.md, Client.Core.Test/AbstractTest.cs, Client.Core/CategoryTraceFilter.cs, Client.Core/InfluxDBTraceFilter.cs, Client.Core/Internal/AbstractQueryClient.cs, Client.Core/Internal/AbstractRestClient.cs, Client.Core/Internal/EnumConverter.cs, Client.Core/Internal/LoggingHandler.cs, Client/InfluxDBClient.cs, Client/Internal/ApiClient.cs, Client/Internal/MeasurementMapper.cs, Client/Internal/RetryAttempt.cs, Client/README.md, Client/UsersApi.cs, Client/WriteApi.cs, Client/WriteApiAsync.cs, Client/Writes/Events.cs
Closes #560 
Allows disable Trace verbose messages
=> feat: #560 disable console log

CHANGELOG.md, Client/InfluxDB.Client.Api/Client/ApiClient.cs, Client/InfluxDB.Client.Api/Service/QueryService.cs, Client/QueryApiSync.cs
Closes #566
Use `HttpCompletionOption.ResponseHeadersRead` for async queries for possibility to use large queries then 2GiB. For more info see related issue.
For more info see: https://www.stevejgordon.co.uk/using-httpcompletionoption-responseheadersread-to-improve-httpclient-performance-dotnet
=> feat: specify http completion for async queries

.circleci/config.yml, CHANGELOG.md, Client.Core/Client.Core.csproj, Client.Legacy/Client.Legacy.csproj, Client.Linq/Client.Linq.csproj, Client/Client.csproj
Closes #574
Changes project files for `Client`, `Client.Core`, `Client.Linq` and `Client.Legacy` to generate XML documentation and include it in nuget packages.
Installed packages before:
```
./packages/influxdb.client/4.15.0/lib/netstandard2.1/InfluxDB.Client.dll
./packages/influxdb.client/4.15.0/lib/netstandard2.0/InfluxDB.Client.dll
...
```
After changes:
```
./packages/influxdb.client/4.15.0-dev/lib/netstandard2.1/InfluxDB.Client.xml
./packages/influxdb.client/4.15.0-dev/lib/netstandard2.1/InfluxDB.Client.dll
./packages/influxdb.client/4.15.0-dev/lib/netstandard2.0/InfluxDB.Client.xml
./packages/influxdb.client/4.15.0-dev/lib/netstandard2.0/InfluxDB.Client.dll
...
```
=> fix: package XML documentation

CHANGELOG.md, Client/QueryApi.cs
Related to https://github.com/influxdata/influxdb-client-csharp/pull/632#discussion_r1685853040
Use `HttpCompletionOption.ResponseHeadersRead` also for async queries for possibility to use large queries then 2GiB.
=> fix: async queries also uses `HttpCompletionOption.ResponseHeadersRead`

CHANGELOG.md, Client.Core/Client.Core.csproj, Client.Core/Internal/AbstractQueryClient.cs, Client.Core/Internal/RestSharpExtensions.cs, Client.Legacy/FluxClient.cs, Client.Test/ItWriteQueryApiTest.cs, Client/InfluxDB.Client.Api/Client/ApiResponse.cs, Client/InvokableScriptsApi.cs, Client/QueryApi.cs, Client/QueryApiSync.cs
Closes #647
This PR upgrade `RestSharp` to `111.4.0` and also migrate our API to new APIs from RestSharp.
=> chore(deps): upgrade RestSharp to `111.4.0`

CHANGELOG.md, Client.Core/Exceptions/InfluxException.cs, Client.Test/InfluxExceptionTest.cs, Client.Test/ItErrorEventsTest.cs, Client.Test/ItWriteApiAsyncTest.cs, Client.Test/WriteApiTest.cs, Client/Writes/Events.cs, Examples/HttpErrorHandling.cs, Examples/README.md, Examples/RunExamples.cs
- Add Headers to `HttpException`
- Make Headers easily accessible in `WriteErrorEvent`
- Add Example showing how to use these changes
- Add tests of these changes
=> feat: add response headers to HttpException

Client.Test/WriteApiTest.cs
The InfluxDB v3 can also return 201 as a successful HTTP code for writes. This PR just adds a test specifically for this status code.
_No need to mention this in the CHANGELOG I guess._
=> test: add test for server returning 201 Created for writes
